### ISSUE TITLE
Cannot find clang-format on some system

### ISSUE THREAD

**Issue by ChaoMai** [LiquidHelium/atom-clang-format#15]
In the file atom-clang-format/lib/main.coffee at line 6, the executable is clang-format. But you may have to use `clang-format + edition number` to call the clang-format in the terminal, like `clang-format-3.5`. So atom-clang-format cannot find the clang-format on some system and throws error.

I know I can create symbol link `clang-format` in `/usr/bin` to `clang-format-3.5`. But the link won't work after the clang-format is updated to new version. Is there any better option without modifying my `/usr/bin`? Can atom-clang-format auto detect the clang-format?

Thanks a lot!

**Comment by LiquidHelium** [comment]
In the settings for the package you should be able to change the executable name.

**Comment by ChaoMai** [comment]
Got it now. Sorry :(

**Comment by LiquidHelium** [comment]
Don't be sorry be happy!
