### ISSUE TITLE
Remove javascript as a default

### ISSUE THREAD

**Issue by szechyjs** [LiquidHelium/atom-clang-format#45]
I spent the last several hours banging my head on my desk as to why all my javascript code was getting screwed up when I save. My last logical place to look was clang-format as it is designed for C/C++ code.

C/C++ formatting standards are not the same as javascript, please remove this default so others don't have to deal with the pain.

**Comment by LiquidHelium** [comment]
You are right, done in cd9b11fea94f21451391200766e97c3a6ea1844e
