### ISSUE TITLE
ClangFormat  Command Failed

### ISSUE THREAD

**Issue by harshaldhake** [LiquidHelium/atom-clang-format#47]
Hi ,

I have already installed the clang format on my Mac however when i tried to applied clang i got below error.

Error:
This error is most often caused by not having clang-format installed and on your path. If you do please create an issue on our github page.

Thanks

**Comment by LiquidHelium** [comment]
Do you have clang-format installed? If so can you open your terminal and run "clang-format --version" and tell me what it says? Thanks!

**Comment by Zialus** [comment]
Same issue here.

`$ clang-format --version`
`clang-format version 3.7.0 (tags/RELEASE_370/final)`

**Comment by Zialus** [comment]
Fixed by adding /usr/local/bin/clang-format to the Executable path on the settings page

**Comment by harshaldhake** [comment]
Zialus,

I am getting below output of version

clang-format harshaldhake$ clang-format --version
clang-format NPM version 1.0.33 at /usr/local/lib/node_modules/clang-format/index.js

I had installed the clang format from NPM from using command 

npm install -g clang-format

I have added the path  which u suggessted but it did not work. Plz suggest

**Comment by bertoldofonseca** [comment]
I'm having the same issue.

```$ clang-format --version
clang-format version 5.0.0 (tags/google/stable/2017-03-17)```

```$ which clang-format
/usr/local/bin/clang-format```

```$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/bin```

**Comment by andrew-aladev** [comment]
Open global atom config.

```
'*':
  core:
    ...

  'clang-format':
    executable: '/usr/local/bin/clang-format'
```

And that's it.

**Comment by andrew-aladev** [comment]
It won't search in `PATH`. See code [here](https://github.com/LiquidHelium/atom-clang-format/blob/master/lib/clang-format.coffee#L43-L49). Looks like `/usr/bin/x86_64/clang-format`. This path is very strange, it won't exist on any linux system as I know.

**Comment by LiquidHelium** [comment]
As of 2.0.6 the error message we give you should be much more detailed. I'm going to close this and then if you experience an error please create a new ticket with the new error message, I'll be in a much better position to help then.

@andrew-aladev I can't see exactly what code you are referencing because it's changed but if its what I think it is that code won't be run if you specify a clang-format binary config option. That code is just for pointing at the bundled binary we include (inside node_modules)

**Comment by andrew-aladev** [comment]
Ok, thank you.
