### ISSUE TITLE
Allow possibility to customize clang-format style

### ISSUE THREAD

**Issue by k4rtik** [LiquidHelium/atom-clang-format#50]
I couldn't find a way to disable inlining of short functions, e.g. the following change:

```
-void
-thread_idle(void)
-{
-  sched_yield();
-}
+void thread_idle(void) { sched_yield(); }
```

It would be great to have some configuration options in the plugin which user can use to pass options to `clang-format`.

**Comment by LiquidHelium** [comment]
You should be able to do this by creating a .clang-format file in your project folder: http://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by k4rtik** [comment]
Got it, thanks! I also had to put the name of the file in Style file config option.

**Comment by k4rtik** [comment]
Hi @LiquidHelium, the settings specified in `.clang-format` don't seem to be respected by the extension. The function still gets inline when I press Cmd-Shift-K

Here's my complete .clang-format FYI:
```
BasedOnStyle: LLVM
AllowShortFunctionsOnASingleLine: None
KeepEmptyLinesAtTheStartOfBlocks: false
```

**Comment by LiquidHelium** [comment]
I assume this has been fixed since you posted this, if it hasn't please re-open
