### ISSUE TITLE
Support for Java and Protobuf

### ISSUE THREAD

**Issue by JayXon** [LiquidHelium/atom-clang-format#51]
The latest clang-format support Java and Protobuf.
http://clang.llvm.org/docs/ClangFormat.html

**Comment by LiquidHelium** [comment]
I'll try and get this done next week once I'm done moving house, shouldn't be too hard to implement.

**Comment by JayXon** [comment]
Any update on this?

**Comment by willdzeng** [comment]
This would be very helpful! Please help us!

**Comment by LiquidHelium** [comment]
I've added support for java in the latest version, but I can't add support for protobuf as atom doesn't have a grammar for it

**Comment by JayXon** [comment]
Thanks, Atom doesn't have built-in support for protobuf but there's a package for it, will that work?
https://atom.io/packages/language-proto
