### ISSUE TITLE
Freeze with Linux kernel code file

### ISSUE THREAD

**Issue by useche** [LiquidHelium/atom-clang-format#52]
I'm trying to use this plugin to edit Linux kernel code. However, everytime I save, the whole editor freezes and start burning CPU at 100%. Unfortunately, I'm not able to read the console. It should be easy to reproduce:
1. Download the kernel code in kernel.org
2. Unzip
3. Open the file block/blk-core.c
4. Save the file

**Comment by LiquidHelium** [comment]
I can't replicate this. It is working for me so I am closing this. This may have been fixed since you reported this.
