### ISSUE TITLE
Line length wrap is truncated at 80 chars

### ISSUE THREAD

**Issue by peekpt** [LiquidHelium/atom-clang-format#54]
I can't change to the desired maximum line length in the code. It's fixed on 80 chars per line.
Your package wraps it to 80 chars .

**Comment by LiquidHelium** [comment]
You need to add 
ColumnLimit: x
to your .clang-format

**Comment by peekpt** [comment]
Thanks! 
on mac:
clang-format -style=llvm -dump-config > .clang-format
and the edit the file

**Comment by peekpt** [comment]
it will be nice if you could pass that parameter from atom config to clang config

**Comment by LiquidHelium** [comment]
I don't think that's within the scope of this project, and probably isn't good practice anyway because then you can't sync your clang-format settings with your git repo.
