### ISSUE TITLE
.clang-format file in subdirectory ignored

### ISSUE THREAD

**Issue by rpavlik** [LiquidHelium/atom-clang-format#61]
I have a project where there's one clang-format style file in the root dir, but then a different one in a subdirectory with source files that should follow a different format. Normally, clang-format will use the one closest to the file, however, this extension appears not to do that - when I save a file in the subdirectory with the alternate clang-format config, I can tell it's definitely not following the subdirectory format, haven't examined closely enough to tell if it's following the in in the project root dir or if it's doing its own thing.

My environment:
I have no custom settings for the extension, except that when I do have it enabled I don't let it format C source files since those I don't usually have a style file for and I don't want to reformat an entire file just to make a one-line change. `config.cson` snippet:

``` cson
  "clang-format":
    formatCOnSave: false
```

Running on Windows, with a somewhat recent official clang/llvm trunk build installed:

```
> clang-format -version
clang-format version 3.9.0 (trunk)
```

and clang-format in my path.

Atom 1.11.1

**Comment by eduardolundgren** [comment]
Any plans to add support for reading `.clang-format` file?

**Comment by collinjackson93** [comment]
The clang-format [documentation](http://clang.llvm.org/docs/ClangFormat.html) states that it looks for the .clang-format file in a parent directory, not subdirectories.
![image](https://cloud.githubusercontent.com/assets/5580739/22608558/05dda0a4-ea23-11e6-9e3b-a229eba7fe79.png)

**Comment by hmaarrfk** [comment]
I guess the point is that if you have the following structure:

````
- .clang-format
- source1.cpp
\----Subdirectory
        - .clang-format
        - source2.cpp
```

source1.cpp should use the top most .clang-format while source2.cpp should use the one in subdirectory.
Is that not the expected behaviour?

**Comment by LiquidHelium** [comment]
Sorry for the long time to respond. This package dosen't do anything with .clang-format files, we just let the clang format do its own thing. You can refer to the documentation posted by collinjackson93 above on how it works. If you would like the behaviour to change I suggest you submit a request to the llvm/clang/clang-format team.
