### ISSUE TITLE
Turn off the format on save action when ther is no .clang-format file

### ISSUE THREAD

**Issue by intijk** [LiquidHelium/atom-clang-format#64]
When the project contains one .clang-format file, we usually want to turn the 'format when save' on. But when there is no .clang-format file, we want to save without changing the indentation, this is really useful. Please consider have that :cat:

**Comment by AndiDog** [comment]
Already solved in #55, just not released yet. Would be nice to just tag a new release.

**Comment by LiquidHelium** [comment]
So sorry, I really should have tagged the release a long long time ago. Thank you for reminding me. I have released a new version now.
