### ISSUE TITLE
1.26.0 Release Not Working [OSX]

### ISSUE THREAD

**Issue by collinjackson93** [LiquidHelium/atom-clang-format#65]
I am on OSX, Atom version 1.13.1. I updated to the latest atom-clang-format release (1.26.0) and found that it does not format files when the keyboard shortcut (cmd-shift-K) is pressed. I installed the previous version (`apm install clang-format@1.25.0`) and found that the keyboard shortcut still works.

I know this isn't much information to go off of, so please let me know what additional information you need.

**Comment by r-owen** [comment]
Do you have a .clang-format file that is a parent directory of the file you are formatting? I didn't and that caused silent failure (in the sense that the plugin would run but it would not do anything).

(My Style and Fallback Style settings are empty -- the default. I am curious what one might be able to put in them. I tried a path to a style file, but silently didn't work).

**Comment by collinjackson93** [comment]
Yes, I have a .clang-format file in a parent directory. I also don't have any overrides in the settings.

I am able to call clang-format from the command line passing the `-style=file` option, so that leads me to believe that clang-format is picking up the .clang-format file properly.

**Comment by r-owen** [comment]
That seems pretty definitive, then. It might be worth a look at the output of the keyword resolver (I don't remember the specifics) to see if anything is colliding, but why it would collide for one version of the software and not another is beyond me.

**Comment by collinjackson93** [comment]
This may not be related, and I don't know CoffeeScript, but [this line](https://github.com/LiquidHelium/atom-clang-format/blob/master/lib/clang-format.coffee#L54) seems a little suspicious. Why is `fallback-style` in quotes, but none of the other options are?

**Comment by collinjackson93** [comment]
I just checked my keybindings and there's definitely nothing colliding with cmd-shift-k.

**Comment by boazsegev** [comment]
Hi :-)

I have the same issue when saving files. I had the clang-format reformat on save, and now nothing seems to happen.

**Comment by collinjackson93** [comment]
@boazsegev So are you seeing that clang-format isn't working when fallback-style isn't set, but it does work when you set it? If so, I think the problem is with the default value that is set for that option.

**Comment by boazsegev** [comment]
@collinjackson93 , I think this might actually be the issue.

If I'm not mistaken, the default (pre-upgrade) was LLVM styling, while post upgrade the default styling is changed to "none"...

So people installing the beautifier and expecting it to "simply work" will be disappointed - as the default behavior is "nothing".

**Comment by collinjackson93** [comment]
Looks like you are correct @boazsegev. It seems like clang-format can't find my .clang-format file. Sorry for any confusion.

**Comment by LiquidHelium** [comment]
I'm going to reopen this and revert back to llvm styling by default when I get some time this weekend. I imagine the change is confusing for most users even if not technically a bug.

**Comment by collinjackson93** [comment]
I just found [this commit](https://reviews.llvm.org/rL292562) that seems to indicate that there's a problem with clang-format if the fallback-style is set to none.

**Comment by LiquidHelium** [comment]
I've set the default fallback to llvm so it should be working as it did now. I've left the fallback option in so you can set it to none if you want that functionality.

**Comment by boazsegev** [comment]
Thanks! I love this package.

And the fallback feature is great :)
