### ISSUE TITLE
No response while Installing clang-format for atom on Mac OS X

### ISSUE THREAD

**Issue by syangav** [LiquidHelium/atom-clang-format#71]
Before try "apm install clang-format", I have installed clang-fomat itself and put it into directory. 
Here is the output when I input "clang-format --version" in terminal 

clang-format version 5.0.0 (tags/google/stable/2017-03-17)

After that I try the command "apm install clang-format", but it always stuck at 
Installing clang-format to /Users/ysh/.atom/packages......

Can anyone help me out? 
By the way, the following is my apm version. 
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.13.1

**Comment by ScrambledAuroras** [comment]
I am trying to fix it but I am unsure where the maintainer is... https://github.com/ScrambledAuroras/atom-clang-format :)

**Comment by LiquidHelium** [comment]
@ScrambledAuroras I am the maintainer, I don't get much time for this anymore though, so I'm slow, sorry :P. Do you know what the issue was exactly? can You elaborate on "misalignment in arguments being passed" I might be able to help fix it.

**Comment by ScrambledAuroras** [comment]
@LiquidHelium It's alright. I don't know CoffeeScript nor JS even but I can read it; I suppose we could work on it. It's an issue with the clang-format call itself, but I'm not sure how to explain it all.

**Comment by LiquidHelium** [comment]
I think this issue might be fixed as of 2.0.5 so i'm going to close this. if it is not fixed let me know and ill look into it
