### ISSUE TITLE
[enhancement] Descriptive Error Message for Invalid .clang-format file

### ISSUE THREAD

**Issue by ChrisRenfrow** [LiquidHelium/atom-clang-format#74]
Error message should be more specific in the case of an invalid .clang-format file instead of showing an obtuse and generally unhelpful error shown below.

<img width="420" alt="screen shot 2017-07-01 at 5 31 36 pm" src="https://user-images.githubusercontent.com/2700549/27766516-73be86a0-5e87-11e7-8cdc-90b065412372.png">

**Comment by LiquidHelium** [comment]
2.0.6 should print better error messages with the stderr of clang-format.
