### ISSUE TITLE
Possible to configure style?

### ISSUE THREAD

**Issue by behrman** [LiquidHelium/atom-clang-format#78]
Is it possible to configure the style atom-clang-format uses?

I would like to configure it to do:

    clang-format -style=Google

Many thanks,

Bill

**Comment by behrman** [comment]
Figured it out.

Thanks

**Comment by cata0309** [comment]
HOOOOOOOW DID YOU DO IT ?????

**Comment by zjgdbansd** [comment]
This is so frustrating. You should be ashamed of yourself, OP.

**Comment by andrew-d-jackson** [comment]
@zjgdbansd There is a `style` option in the config page for the package, it defaults to file. You can change it in there or create a `.clang-format` file in your projects root folder and give it some values, such as a `BasedOnStyle`. More reading: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
