### ISSUE TITLE
custom path to clang-format

### ISSUE THREAD

**Issue by davydden** [LiquidHelium/atom-clang-format#80]
would be good to have a setting to specify a custom path to `clang-format`. 

Same applies to the settings `.clang-format`, in case one has a single setting file to be used with all projects.

**Comment by LiquidHelium** [comment]
Sorry for taking so long to reply. There is currently a setting to specify a clang-format binary location. As for .clang-format, we don't manually use .clang-format at all in this package, we just let clang-format do its thing. Check out the clang format docs for how to have a project only .clang-format file
