### ISSUE TITLE
Format on Save not working

### ISSUE THREAD

**Issue by nijaru** [LiquidHelium/atom-clang-format#81]
Format on save is not working for me in Atom 1.25.0, but it worked previously.

Calling the command does work

**Comment by tikonen** [comment]
Try to remove quote marks around the path to clang-format executable in the plugin config.
![image](https://user-images.githubusercontent.com/380448/39088845-47a34ea2-45c2-11e8-8310-b6ba63b05fee.png)

**Comment by LiquidHelium** [comment]
Sorry for the long time to reply. Did the above comment by @tikonen fix it? I'm going to assume it did and close this issue, if you are still experiencing the error let me know and I'll look into it.
