### ISSUE TITLE
use globle default .clang-format

### ISSUE THREAD

**Issue by spicalai** [LiquidHelium/atom-clang-format#82]
hi,

while using atom-clang-format to format the code, there should be a default .clang-format file that is used, otherwise, the one in source folder or parent folder will be used.
but I wanna change the default .clang-format file. how can I do that?
where is the location of the default one?

**Comment by LiquidHelium** [comment]
This is not within the scope of this package. We don't do anything manually with .clang-format files, we just let clang-format do its thing. You should be able to set a global .clang-format file by putting one high up in your file system. You can read the clang-format docs here to find out more: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
